site_name: inretensys-fastapi
site_url: https://github.com/in-RET/inretensys-fastapi/
site_author: Andreas Lubojanski

# Repository
repo_name: in-RET/inretensys-fastapi
repo_url: https://github.com/in-RET/inretensys-fastapi

markdown_extensions:
    - toc:
        permalink: true
    - attr_list
    - md_in_html
    - pymdownx.highlight:
          anchor_linenums: true
          use_pygments: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
    - 'Home': index.md
    - 'API': 
        - 'Overview': api/api.md
        - 'Usage with Python': api/python.md
        - 'Functions': api/functions.md
    - 'About': about.md
    - 'Release Notes': release-notes.md
theme:
    name: material
    icon:
        repo: fontawesome/brands/github
    palette:
        scheme: slate
        primary: teal
        accent: teal
    language: de
extra_css:
  - stylesheets/extra.css
extra:
    social:
        - icon: fontawesome/solid/envelope
          link: mailto:andreas.lubojanski@hs-nordhausen.de
    generator: true
copyright: Copyright &copy; 2022 Institut für regnenrative Energietechnik
    