FROM python:3.9-slim-bullseye

WORKDIR /api

COPY ./requirements.txt /requirements.txt
COPY ./external/ /external

RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir --upgrade /external/InRetEnsys-0.2a2-py3-none-any.whl
RUN pip install --no-cache-dir --upgrade -r /requirements.txt

COPY ./ /api/

WORKDIR /

CMD [ "uvicorn", "api.api:app", "--host", "0.0.0.0", "--port", "8000" ]